name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v3

      # This has to be done before setting up Node.js,
      # more info found in https://github.com/actions/setup-node/issues/531#issuecomment-1872977503
      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install

      - name: test, report coverage
        run: |
          pnpm build
          pnpm test:lint
          pnpm coverage

      - uses: codecov/codecov-action@v1
        if: success() && matrix.os == 'ubuntu-latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
